year score function
fykosak/fks-texmf pull request #80
Opened 2020-12-01 18:29 UTC by rzehumat

Meggy's function
> můj hotfix, který přepočítává procenta za minulé série na procenta za celý ročník

Necessary to make batches -- otherwise making the list of participants will fail. Before it was manually written to every batch*/batch*.tex, which is a bad practice

TODO: rename it. Name `hotfix` is to be avoided. But I don't know, where is it used.

2020-12-02 10:46 UTC, rzehumat commented
See [https://github.com/fykosak/fks-templates/pull/20](url) as well

2020-12-02 17:42 UTC, tuaki requested changes
Dopiš prosím do komentářů nad funkcí o jaká přesně procenta se jedná. Jakože procenta z čeho na co a tak, teď mi není úplně jasné co přesně znamená současný komentář. Dále, last series' znamená poslední sérii (teda 6.), nebo poslední zveřejněnou sérii (potom bych spíš napsal něco jako current / previous)?

2021-01-23 11:56 UTC, rzehumat commented
> je to můj hotfix, který přepočítává procenta za minulé série na procenta za celý ročník

WTF, takže má jít o výpočet "kolik zatím mají bodů z celkového počtu bodů za ročník"??? Uměl by to někdo nějak zkontrolovat?

2021-01-25 10:48 UTC, cevro commented
Nemal by sa počet bodov za ročník ťahať po správnosti z FKSDB?

2021-01-25 11:14 UTC, rzehumat commented
Souhlasím @cevro. Možná si právě vyřešil, proč mi ten skript ani ta čísla nedávají smysl.

2022-12-20 23:49 UTC, closed without merging